SystemPraktyk/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace SystemPraktyk.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

SystemPraktyk/Pages/InfoPraktyki.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SystemPraktyk.Pages
{
    public class InfoPraktykiModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SystemPraktyk/Pages/MojeWnioski.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SystemPraktyk.Pages
{
    public class MojeWnioskiModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SystemPraktyk/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SystemPraktyk.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

SystemPraktyk/Pages/ZlozWniosek.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SystemPraktyk.Pages
{
    public class ZlozWniosekModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SystemPraktyk/Pages/podanie.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SystemPraktyk.Pages
{
    public class podanieModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SystemPraktyk/Pages/wniosek.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace SystemPraktyk.Pages
{
    public class wniosekModel : PageModel
    {
        public void OnGet()
        {
        }
        public IActionResult OnPostSubmit(FormData formData)
        {
            string jsonString = JsonConvert.SerializeObject(formData, Formatting.Indented);
            string filePath = "plik.json";
            System.IO.File.WriteAllText(filePath, jsonString);

            return new JsonResult(new { status = "success", data = formData });
        }

        public class FormData
        {
            [BindProperty]
            public string CompanyAddress { get; set; }
            [BindProperty]
            public string KrsNumber { get; set; }
            [BindProperty]
            public string NipNumber { get; set; }
            [BindProperty]
            public string CompanyCeo { get; set; }
            [BindProperty]
            public string InternDateSelect { get; set; }
            [BindProperty]
            public string startDateOfIntern { get; set; }
            [BindProperty]
            public string endDateOfIntern { get; set; }
        }
    }
}

SystemPraktyk/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h5 class="display-8">
        Zasady i program odbywania praktyk studenckich <br />
        na Wydziale Elektrotechniki, Automatyki i Informatyki <br />
        Politechniki Świętokrzyskiej <br />
        dla studiów o profilu akademickim<br />
    </h5>
    <p>Więcej na temat praktyk: <a href="/InfoPraktyki">Informacje na temat praktyk</a>.</p>
</div>

<div class="text-center">
    <button id="buttonMojeWnioski" class="btn btn-primary">Moje wnioski</button> <br />
    <br />
    <button id="buttonZlozWniosek" class="custom-button">Złóż wniosek</button>
</div>

<script>
    document.getElementById('buttonMojeWnioski').addEventListener('click', function () {
        window.location.href = '/MojeWnioski';
    });

    document.getElementById('buttonZlozWniosek').addEventListener('click', function () {
        window.location.href = '/ZlozWniosek';
    });
</script>

SystemPraktyk/Pages/InfoPraktyki.cshtml
@page
@model SystemPraktyk.Pages.InfoPraktykiModel
@{
}
<div class="text-center">
    <h1 class="display-4">Informacje na temat praktyk</h1>
    Na wniosek {PDF} Rektora Politechniki Świętokrzyskiej z dnia 20 września 2019 r. w sprawie Regulaminu Praktyk Zawodowych w Politechnice Świętokrzyskiej (ze zmianami) oraz programem studiów realizowanym na poszczególnych kierunkach studiów o profilu akademickim na Wydziale Elektrotechniki, Automatyki i Informatyki student zobowiązany jest do odbycia czterotygodniowej praktyki.  Praktyki studenckie stanowią integralną część procesu kształcenia i podlegają zaliczeniu. Dotyczy to zarówno studentów studiów stacjonarnych jak i niestacjonarnych. Studenci odbywają praktykę w okresie wakacyjnym przed rozpoczęciem V lub VII semestru studiów I stopnia (w zależności od kierunku studiów). Głównym celem praktyki studenckiej jest m.in.:

    umiejętne wykorzystanie wiedzy zdobytej na studiach w pracy zawodowej;
    przygotowanie studenta do pracy w zespole, ale także do samodzielnego wykonywania powierzonych mu zadań;
    pogłębianie wiedzy o branżach gospodarki, poznanie zasad organizacji przedsiębiorstw i mechanizmów ich funkcjonowania.

    Praktyka studencka może być odbywana w wybranym przez studenta podmiocie gospodarczym, instytucji lub zakładzie o profilu umożliwiającym zrealizowanie celów określonych w programie praktyk.

    Student we własnym zakresie wyszukuje miejsce odbywania praktyki, przedstawia propozycję Kierownikowi ds. praktyk studenckich na Wydziale (odpowiednio dla danego kierunku studiów) w celu uzyskania akceptacji. Po uzyskaniu zgody student składa w wybranym przez siebie zakładzie pracy podanie z prośbą o przyjęcie na praktykę (w przypadku gdy tego wymaga pracodawca). Warunki realizacji praktyki przez studenta określa Umowa zawarta pomiędzy Politechniką Świętokrzyską i pracodawcą. Praktyka ma z reguły charakter nieodpłatnej pracy na rzecz danego zakładu pracy. Uczelnia nie ubezpiecza studentów – praktykantów od następstw nieszczęśliwych wypadków (NW). Decyzję o ewentualnym ubezpieczeniu student podejmuje samodzielnie.
</div>
<div class="text-center">
    <br />
    <br />
    <br />
    <br />
</div>
<div class="text-center">
    <h1 class="display-4">Zaliczenie praktyk</h1>
    Student w terminie do 8.09.2023 r. zgłasza się osobiście do opiekuna praktyk ze strony Uczelni celem zaliczenia praktyki. Student zobowiązany jest dostarczyć:

    opcjonalnie indeks (wpisany rok akademicki, nazwa i adres zakładu pracy, czas trwania praktyki w tygodniach) – wpis na oznaczonych, końcowych stronach indeksu,
    Sprawozdanie z praktyki studenckiej – załącznik nr 3 poświadczone przez zakładowego opiekuna praktyk (podpis i pieczęć).

    Sprawozdanie z praktyki powinno stanowić szczegółowy opis prac wykonanych przez praktykanta podczas całego okresu praktyki. Sprawozdanie powinno zawierać:

    charakterystykę zakładu pracy,
    szczegółowy opis przebiegu praktyki,
    podsumowanie praktyki (zdobyta wiedza, umiejętności, uwagi i wnioski).

    Zaliczenia praktyki zawodowej dokonuje w indeksie Opiekun praktyk studenckich na podstawie wymienionych wyżej dokumentów oraz rozmowy ze studentem o przebiegu praktyki i realizacji jej celu. Sprawozdanie z praktyki oraz Umowa zamieszczone zostają w aktach osobowych studenta.

    W przypadku posiadanego doświadczenia zawodowego (umowa o pracę / umowa o dzieło / umowa zlecenie / własna działalność) zgodnego z kierunkiem studiów i wypełniającego wymagane efekty uczenia się (karta przedmiotu) można złożyć podanie o zaliczenie praktyk wraz z odpowiednią dokumentacją poświadczającą przepracowanie 160h (kserokopie potwierdzone w Dziekanacie).
</div>

SystemPraktyk/Pages/MojeWnioski.cshtml
@page
@model SystemPraktyk.Pages.MojeWnioskiModel
@{
}
<div>
    <h1>
        Moje Wnioski TODO
    </h1>
</div>

SystemPraktyk/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SystemPraktyk</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SystemPraktyk.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SystemPraktyk/css/Styles.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: #FC9C41;">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">
                    <img src="img/akronim-weaii-krotki.png" alt="Zdjecie System Praktyk PŚK"/>    
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link white-text-black-shadow" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link white-text-black-shadow" asp-area="" asp-page="/MojeWnioski">Moje Wnioski</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link white-text-black-shadow" asp-area="" asp-page="/ZlozWniosek">Złóż Wniosek</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link white-text-black-shadow" asp-area="" asp-page="/Privacy">Ustawienia</a>
                        </li>                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SystemPraktyk - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SystemPraktyk/Pages/ZlozWniosek.cshtml
@page
@model SystemPraktyk.Pages.ZlozWniosekModel
@{
}
<div class="text-center">
    <select id="documentSelect">
        <option value="">Wybierz wniosek: </option>
        <option value="document1">Wniosek o praktyki</option>
        <option value="document2">Podanie o praktyki</option>
    </select>
</div>

<script type="text/javascript">
    document.getElementById('documentSelect').addEventListener('change', function () {
        var value = this.value;
        if (value === 'document1') {
            window.location.href = '/wniosek';
        } else if (value === 'document2') {
            window.location.href = '/podanie';
        }
    });
</script>

SystemPraktyk/Pages/podanie.cshtml
@page
@model SystemPraktyk.Pages.podanieModel
@{
}
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    podanie
</div>

SystemPraktyk/Pages/wniosek.cshtml
@page
@model SystemPraktyk.Pages.wniosekModel
@{
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <form method="post" asp-page-handler="Submit">
        <label for="CompanyAddress">Nazwa firmy:</label>
        <br />
        <input type="text" id="CompanyAddress" name="CompanyAddress" />
        <br />
        <label for="KrsNumber">Numer KRS:</label>
        <br />
        <input type="text" id="KrsNumber" name="KrsNumber" />
        <br />
        <label for="NipNumber">Numer NIP:</label>
        <br />
        <input type="text" id="NipNumber" name="NipNumber" />
        <br />
        <label for="CompanyCeo">CEO Firmy:</label>
        <br />
        <input type="text" id="CompanyCeo" name="CompanyCeo" />
        <br />
        <br />

        <select id="internDateSelect">
            <option value="default">Wybierz date praktyk: </option>
            <option value="dateJuly">Lipcowe</option>
            <option value="dateAugust">Sierpniowe</option>
            <option value="dateSeptember">Wrześniowe</option>
        </select>
        <br />
        <br />

        <button type="submit" class="btn btn-primary">Wyślij</button>
    </form>

</div>

<script type="text/javascript">
    var startDateOfIntern, endDateOfIntern;
    document.getElementById('internDateSelector').addEventListener('change', function () {
        var value = this.value;
        if (value === 'dateJuly') {
            startDateOfIntern = '03.07.2023';
            endDateOfIntern = '28.07.2023';
        } else if (value === 'dateAugust') {
            startDateOfIntern = '03.08.2023';
            endDateOfIntern = '28.08.2023';
        } else if (value == 'dateSeptember') {
            startDateOfIntern = '03.09.2023';
            endDateOfIntern = '28.09.2023';
        }else{
            alert("Musisz wybrać date praktyk");
            startDateOfIntern = null;
            endDateOfIntern = null;

        }
    });

        document.querySelector('form').addEventListener('submit', function (e) {
            e.preventDefault();

            var formData = {
                companyAddress: document.getElementById('company_address').value,
                krsNumber: document.getElementById('krs_number').value,
                nipNumber: document.getElementById('nip_number').value,
                companyCeo: document.getElementById('company_ceo').value,
                internDateSelect: document.getElementById('internDateSelect').value,
                startDateOfIntern: startDateOfIntern,
                endDateOfIntern: endDateOfIntern
            };

            sendData(formData);
        });

    function sendData(data) {
        fetch('/wniosek?handler=Submit', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify(data)
        })
            .then(response => response.json())
            .then(data => {
                console.log('Sukces:', data);
            })
            .catch((error) => {
                console.error('Błąd:', error);
            });
    }
</script>